server:
  port: 80

spring:
  application:
    name: cloud-consumer-com.zzz.springcloud.order-from-eureka
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/com.zzz.springcloud.order?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zzz.springcloud.com.zzz.cloud.common.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

ribbon:
  # 指建立连接的时间，网络正常情况下两端建立连接的时间
  ReadTimeout: 5000
  # 指建立连接后从服务端读取资源所用时间
  ConnectTimeout: 5000

logging:
  level:
    # feign以什么日志级别检测什么接口
    com.zzz.springcloud.order.service.PaymentService: debug

feign:
  hystrix:
    #开启豪猪哥支持
    enabled: true
