server:
  port: 7002
eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: eureka02.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka01.com:7001/eureka
spring:
  application:
    name: cloud-eureka-server01
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/payment?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
