server:
  port: 80

spring:
  cloud:
    zookeeper:
      connect-string: 1.117.165.175:2181
  application:
    name: cloud-consumer-com.zzz.springcloud.order-from-zookeeper

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zzz.springcloud.com.zzz.springcloud.payment.entity

