server:
  port: 9527

spring:
  application:
    name: cloud-gateaway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心开启动态路由功能，利用微服务名进行路由(自动负载均衡)
      routes:
        - id: payment-server #路由ID
#          uri: http://localhost:8001 #匹配后提供的路由地址 （不开启动态路由配置示例）
          uri: lb://CLOUD-PROVIDER-PYMENT-FOR-EUREKA-HYSTRIX # 根据服务名路由，自动负载均衡
          predicates:
            - Path=/payment/** #断言，需要匹配的路径·
            - After=2021-07-12T13:01:00.500+08:00[Asia/Shanghai] #表示路径匹配 且 时间在这之后才路由（同理Before,Between）
            # - Cookie=username,zzz #表示需要Cookie含有username为zzz才路由

eureka:
  instance:
    # 设置服务显示名称
    instance-id: payment01
    # 开启IP显示
    prefer-ip-address: true
    # 发送心跳间隔（秒）
    lease-renewal-interval-in-seconds: 5
    # 服务器收到最后一次心跳等待时间上限（秒）
    lease-expiration-duration-in-seconds: 10

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
#      defaultZone: http://localhost:7001/eureka

