server:
  port: 80

spring:
  cloud:
    consul:
      host: 1.117.165.175
      port: 8500
  application:
    name: cloud-consumer-order-from-consul

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zzz.springcloud.common.entity

